### ISSUE TITLE
Trouble installing on mac osx (Yosemite, 10.10.5)

### ISSUE THREAD

**Issue by jmichaux** [nadavbh12/Retro-Learning-Environment#15]
I cloned the repo and followed the installation instructions, but the installation failed.  I appreciate any help.

Here's the output:

(rle) :build jmichaux$ make -j 4
Scanning dependencies of target genesis_plus_gx_libretro
Scanning dependencies of target stella_libretro
Scanning dependencies of target rle-lib
Scanning dependencies of target rle-c-lib
[  0%] Creating directories for 'stella_libretro'
[  1%] Creating directories for 'genesis_plus_gx_libretro'
[  2%] Performing download step (git clone) for 'genesis_plus_gx_libretro'
[  3%] Performing download step (git clone) for 'stella_libretro'
Cloning into 'stella-libretro'...
Cloning into 'Genesis-Plus-GX'...
[  4%] Building CXX object CMakeFiles/rle-lib.dir/src/rle_interface.cpp.o
[  5%] Building CXX object CMakeFiles/rle-c-lib.dir/rle_python_interface/rle_c_wrapper.cpp.o
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[  6%] Building CXX object CMakeFiles/rle-c-lib.dir/src/rle_interface.cpp.o
In file included from /Users/jmichaux/Retro-Learning-Environment/src/rle_interface.cpp:32:
In file included from /Users/jmichaux/Retro-Learning-Environment/src/environment/RleSystem.hxx:37:
In file included from /Users/jmichaux/Retro-Learning-Environment/src/environment/../common/display_screen.h:24:
/Users/jmichaux/Retro-Learning-Environment/src/common/../environment/RetroAgent.h:10:10: fatal error: 
      'SDL/SDL_rotozoom.h' file not found
#include "SDL/SDL_rotozoom.h"
         ^
1 error generated.
make[2]: *** [CMakeFiles/rle-lib.dir/src/rle_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/rle-lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/Constants.cpp.o
In file included from /Users/jmichaux/Retro-Learning-Environment/src/common/Constants.cpp:16:
In file included from /Users/jmichaux/Retro-Learning-Environment/src/common/Constants.h:20:
/Users/jmichaux/Retro-Learning-Environment/src/common/DebugMacros.h:20:17: warning: using directive refers to
      implicitly-defined namespace 'std'
using namespace std;
                ^
[  8%] No patch step for 'stella_libretro'
[  9%] No update step for 'stella_libretro'
[ 10%] No configure step for 'stella_libretro'
[ 11%] Performing build step for 'stella_libretro'
In file included from /Users/jmichaux/Retro-Learning-Environment/src/rle_interface.cpp:32:
In file included from /Users/jmichaux/Retro-Learning-Environment/src/environment/RleSystem.hxx:37:
In file included from /Users/jmichaux/Retro-Learning-Environment/src/environment/../common/display_screen.h:24:
/Users/jmichaux/Retro-Learning-Environment/src/common/../environment/RetroAgent.h:10:10: fatal error: 
      'SDL/SDL_rotozoom.h' file not found
#include "SDL/SDL_rotozoom.h"
         ^
1 warning generated.
1 error generated.
make[2]: *** [CMakeFiles/rle-c-lib.dir/src/rle_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/rle-c-lib.dir/all] Error 2
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 11%] No patch step for 'genesis_plus_gx_libretro'
[ 12%] No update step for 'genesis_plus_gx_libretro'
[ 13%] No configure step for 'genesis_plus_gx_libretro'
[ 14%] Performing build step for 'genesis_plus_gx_libretro'
In file included from stella/src/emucore/PropsSet.cxx:31:
stella/src/emucore/PropsSet.hxx:129:14: warning: private field 'myOSystem' is not used [-Wunused-private-field]
    OSystem* myOSystem;
             ^
1 warning generated.
stella/src/emucore/StateManager.cxx:57:7: warning: reference cannot be bound to dereferenced null pointer in
      well-defined C++ code; pointer may be assumed to always convert to true [-Wundefined-bool-conversion]
  if(&myOSystem->console())
  ~~  ^~~~~~~~~~~~~~~~~~~~
stella/src/emucore/OSystem.hxx:130:14: note: 'console' returns a reference
    Console& console() const { return *myConsole; }
             ^
stella/src/emucore/StateManager.cxx:77:9: warning: reference cannot be bound to dereferenced null pointer in
      well-defined C++ code; pointer may be assumed to always convert to true [-Wundefined-bool-conversion]
    if(&myOSystem->console())
    ~~  ^~~~~~~~~~~~~~~~~~~~
stella/src/emucore/OSystem.hxx:130:14: note: 'console' returns a reference
    Console& console() const { return *myConsole; }
             ^
In file included from stella/src/emucore/StateManager.cxx:31:
stella/src/emucore/StateManager.hxx:95:9: warning: private field 'myCurrentSlot' is not used
      [-Wunused-private-field]
    int myCurrentSlot;
        ^
3 warnings generated.
core/tremor/sharedbook.c:215:6: warning: absolute value function 'abs' given an argument of type 'long' but has
      parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
                                 abs(b->quantlist[index]),&point);
                                 ^
core/tremor/sharedbook.c:215:6: note: use function 'labs' instead
                                 abs(b->quantlist[index]),&point);
                                 ^~~
                                 labs
core/tremor/sharedbook.c:249:6: warning: absolute value function 'abs' given an argument of type 'long' but has
      parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
                                 abs(b->quantlist[j*b->dim+k]),&point);
                                 ^
core/tremor/sharedbook.c:249:6: note: use function 'labs' instead
                                 abs(b->quantlist[j*b->dim+k]),&point);
                                 ^~~
                                 labs
2 warnings generated.
libretro/libretro.c:1744:39: warning: comparison of constant 1025 with expression of type 'unsigned char' is
      always false [-Wtautological-constant-out-of-range-compare]
         if (port && (input.system[0] >= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DE...
                      ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1744:93: warning: comparison of constant 2049 with expression of type 'unsigned char' is
      always true [-Wtautological-constant-out-of-range-compare]
  ...>= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DEVICE_MSPAD_2B_MASTERTAP))
                                           ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1753:39: warning: comparison of constant 1025 with expression of type 'unsigned char' is
      always false [-Wtautological-constant-out-of-range-compare]
         if (port && (input.system[0] >= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DE...
                      ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1753:93: warning: comparison of constant 2049 with expression of type 'unsigned char' is
      always true [-Wtautological-constant-out-of-range-compare]
  ...>= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DEVICE_MSPAD_2B_MASTERTAP))
                                           ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1762:39: warning: comparison of constant 1025 with expression of type 'unsigned char' is
      always false [-Wtautological-constant-out-of-range-compare]
         if (port && (input.system[0] >= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DE...
                      ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1762:93: warning: comparison of constant 2049 with expression of type 'unsigned char' is
      always true [-Wtautological-constant-out-of-range-compare]
  ...>= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DEVICE_MSPAD_2B_MASTERTAP))
                                           ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1846:39: warning: comparison of constant 1025 with expression of type 'unsigned char' is
      always false [-Wtautological-constant-out-of-range-compare]
         if (port && (input.system[0] >= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DE...
                      ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro/libretro.c:1846:93: warning: comparison of constant 2049 with expression of type 'unsigned char' is
      always true [-Wtautological-constant-out-of-range-compare]
  ...>= RETRO_DEVICE_MDPAD_3B_WAYPLAY) && (input.system[0] <= RETRO_DEVICE_MSPAD_2B_MASTERTAP))
                                           ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 warnings generated.
[ 15%] No install step for 'genesis_plus_gx_libretro'
[ 15%] Completed 'genesis_plus_gx_libretro'
[ 15%] Built target genesis_plus_gx_libretro
[ 16%] No install step for 'stella_libretro'
[ 17%] Completed 'stella_libretro'
[ 17%] Built target stella_libretro
make: *** [all] Error 2

**Comment by nadavbh12** [comment]
It looks like you're missing a dependency `libsdl-gfx1.2-dev` .
Other than that I haven't tried installing the repo on mac, and never worked with mac actually. So I'm guessing there will be more issues.
I can try and help on the newer issues, if you wish to try and get it to work.
