### ISSUE TITLE
python_interface gives wrong game screen dimensions

### ISSUE THREAD

**Issue by CKMagenta** [nadavbh12/Retro-Learning-Environment#16]
* Ubuntu 16.04
* using python interface to work with RLE.
* I used the option "-DUSE_SDL=ON" in setup.py to see actual game screen
* I run "sonic_the_hedgehog"

I tried to get grayscale game screen by calling the following method of the python interface:
`def getScreenGrayscale(self, screen_data=None)`
, and there was two problems (, which is actually coming from one source)

It gave me an array of grayscale pixel data, however, the screen was totally distorted.
I played with it for a while, I noticed that it's because the method initializes `screen_data` variable with wrong number of pixels in a row and col when I did not pass `screen_data` variable.
I could guess right width (640 px), and able to get clean data by passing `screen_data` with right dimensions.

Also, I noticed another problem: Even though I pass `screen_data` variable initialized in right size, the `screen_data` array is not fully filled, but have many zeros in the tail.

When `getScreenGrayscale` is called in the python interface, it calls 
`void getScreenGrayscale(RLEInterface *rle, unsigned char *output_buffer)` in rle_c_wrapper.cpp which calls :
`size_t w = rle->getScreen().width();`
`size_t h = rle->getScreen().height();`

The cause of the problem is that the last two methods gives wrong values.
I could pass `screen_data` numpy matrix to the python interface method, but when c method received the matrix, the matrix is viewed as an one dimensional pointer variable, which does not have dimensional information, and the right dimension that even explicitly specified in python-side could not passed to c-side.

For the same reason, the following methods in `rle_c_wrapper.h` also does not work properly.
`int getScreenWidth(RLEInterface *rle){return rle->getScreen().width();}`
`int getScreenHeight(RLEInterface *rle){return rle->getScreen().height();}`
, which is being used in following methods in `rle_python_interface.py`
`def getScreenRGB(self, screen_data=none)`
`def getScreenGrayscale(self, screen_data=none)`

I made a method 
`void getScreenGrayscaleWithDims(RLEInterface*, unsigned char*, size_t width, size_t height)`
and used it instead of 
`void getScreenGrayscale(RLEInterface *rle, unsigned char *output_buffer)`
in order to specify dimensions explicitly
, and it works fine. 
I could get screen_data in undistorted and right size with fully filled pixel data.

Though ultimately Screen.width(), height() methods need to be fixed, let me send a pull request if it is looking good.

**Comment by nadavbh12** [comment]
@CKMagenta 
Thanks for looking into this thoroughly. I prefer to solve the issue by fixing the retrieval of width and height directly.
Hope to get to it in the next few days.
