### ISSUE TITLE
Trouble installing on AWS

### ISSUE THREAD

**Issue by jmichaux** [nadavbh12/Retro-Learning-Environment#18]
Hi Nadav,

Sorry to bother you with this again.  I'm now trying to install RLE on AWS EC2.  I get the following errors.  Do you have any tips?  Thanks.

ubuntu@ip-172-31-48-241:~/Retro-Learning-Environment/build$ make -j 4
Scanning dependencies of target genesis_plus_gx_libretro
Scanning dependencies of target rle-lib
Scanning dependencies of target rle-c-lib
Scanning dependencies of target snes9x2010_libretro
[  1%] [  1%] Creating directories for 'genesis_plus_gx_libretro'
Creating directories for 'snes9x2010_libretro'
[  2%] [  3%] Building CXX object CMakeFiles/rle-lib.dir/src/rle_interface.cpp.o
Building CXX object CMakeFiles/rle-c-lib.dir/rle_python_interface/rle_c_wrapper.cpp.o
[  4%] Performing download step (git clone) for 'genesis_plus_gx_libretro'
[  5%] Performing download step (git clone) for 'snes9x2010_libretro'
Cloning into 'Genesis-Plus-GX'...
Cloning into 'snes9x2010'...
remote: Counting objects: 9257, done.
remote: Counting objects: 7096, done.
remote: Total 7096 (delta 0), reused 0 (delta 0), pack-reused 7096
Receiving objects: 100% (7096/7096), 31.21 MiB | 16.17 MiB/s, done.
Resolving deltas: 100% (4959/4959), done.9 MiB | 13.42 MiB/s
remote: Total 9257 (delta 0), reused 0 (delta 0), pack-reused 9256
Receiving objects: 100% (9257/9257), 53.84 MiB | 15.17 MiB/s, done.
Resolving deltas: 100% (6671/6671), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Checking connectivity... done.
[  6%] No patch step for 'snes9x2010_libretro'
[  7%] No update step for 'snes9x2010_libretro'
[  8%] No configure step for 'snes9x2010_libretro'
[  9%] Performing build step for 'snes9x2010_libretro'
src/apu.c: In function ‘spc_copier_copy_int’:
src/apu.c:1240:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  SET_LE16( s, state );
  ^
src/apu.c:1242:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  return GET_LE16( s );
  ^
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 10%] No patch step for 'genesis_plus_gx_libretro'
[ 11%] No update step for 'genesis_plus_gx_libretro'
[ 11%] No configure step for 'genesis_plus_gx_libretro'
[ 12%] Performing build step for 'genesis_plus_gx_libretro'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [genesis_plus_gx_libretro-prefix/src/genesis_plus_gx_libretro-stamp/genesis_plus_gx_libretro-build] Error 2
make[1]: *** [CMakeFiles/genesis_plus_gx_libretro.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object CMakeFiles/rle-c-lib.dir/src/rle_interface.cpp.o
src/dsp.c: In function ‘DSP4_READ_WORD’:
src/dsp.c:3307:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  out = READ_WORD(DSP4.parameters + DSP4.in_index);
  ^
src/dsp.c: In function ‘DSP4_READ_DWORD’:
src/dsp.c:3317:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  out = READ_DWORD(DSP4.parameters + DSP4.in_index);
  ^
src/dsp.c: In function ‘DSP4_OP01’:
src/dsp.c:3416:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD((DSP4.world_x + DSP4.world_xenv) >> 16);
   ^
src/dsp.c:3417:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_x2);
   ^
src/dsp.c:3418:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.world_y >> 16);
   ^
src/dsp.c:3419:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_y2);
   ^
src/dsp.c:3444:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.segments);
   ^
src/dsp.c:3470:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
     ^
src/dsp.c:3471:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
     ^
src/dsp.c:3472:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
     ^
src/dsp.c: In function ‘DSP4_OP07’:
src/dsp.c:3634:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_x2);
   ^
src/dsp.c:3635:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_y2);
   ^
src/dsp.c:3660:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.segments);
   ^
src/dsp.c:3686:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
     ^
src/dsp.c:3687:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
     ^
src/dsp.c:3688:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
     ^
src/dsp.c: In function ‘DSP4_OP08’:
src/dsp.c:3861:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  DSP4_WRITE_BYTE(win_left  & 0xff);
  ^
src/dsp.c:3862:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  DSP4_WRITE_BYTE(win_right & 0xff);
  ^
src/dsp.c:3941:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

    DSP4_WRITE_WORD(DSP4.segments);
    ^
src/dsp.c:4022:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

      DSP4_WRITE_WORD(DSP4.poly_ptr[polygon][0]);
      ^
src/dsp.c:4023:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

      DSP4_WRITE_BYTE(x_left  & 0xff);
      ^
src/dsp.c:4024:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

      DSP4_WRITE_BYTE(x_right & 0xff);
      ^
src/dsp.c:4042:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

  DSP4_WRITE_WORD(0);
  ^
src/dsp.c: In function ‘DSP4_OP0B’:
src/dsp.c:4092:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(1);
   ^
src/dsp.c:4095:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_BYTE(sp_x & 0xff);
   ^
src/dsp.c:4096:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_BYTE(sp_y & 0xff);
   ^
src/dsp.c:4097:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(sp_attr);
   ^
src/dsp.c:4119:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(0);
   ^
src/dsp.c: In function ‘DSP4_OP09’:
src/dsp.c:4233:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

    DSP4_WRITE_WORD(world_spx);
    ^
src/dsp.c: In function ‘DSP4_OP0D’:
src/dsp.c:4444:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD((DSP4.world_x + DSP4.world_xenv) >> 16);
   ^
src/dsp.c:4445:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_x2);
   ^
src/dsp.c:4446:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.world_y >> 16);
   ^
src/dsp.c:4447:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_y2);
   ^
src/dsp.c:4473:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.segments);
   ^
src/dsp.c:4500:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
     ^
src/dsp.c:4501:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
     ^
src/dsp.c:4502:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
     ^
src/dsp.c: In function ‘DSP4_OP0F’:
src/dsp.c:4636:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD((DSP4.world_x + DSP4.world_xenv) >> 16);
   ^
src/dsp.c:4637:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_x2);
   ^
src/dsp.c:4638:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.world_y >> 16);
   ^
src/dsp.c:4639:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_y2);
   ^
src/dsp.c:4665:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.segments);
   ^
src/dsp.c:4701:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

      DSP4_WRITE_WORD(color);
      ^
src/dsp.c:4725:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
     ^
src/dsp.c:4726:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
     ^
src/dsp.c:4727:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
     ^
src/dsp.c: In function ‘DSP4_OP10’:
src/dsp.c:4872:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_x2);
   ^
src/dsp.c:4873:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.view_y2);
   ^
src/dsp.c:4898:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

   DSP4_WRITE_WORD(DSP4.segments);
   ^
src/dsp.c:4931:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

      DSP4_WRITE_WORD(color);
      ^
src/dsp.c:4962:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
     ^
src/dsp.c:4963:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
     ^
src/dsp.c:4964:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
     ^
src/dsp.c: In function ‘DSP4_SetByte’:
src/dsp.c:5096:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(product);
     ^
src/dsp.c:5097:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(product >> 16);
     ^
src/dsp.c:5149:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(out1a);
     ^
src/dsp.c:5150:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(out2a);
     ^
src/dsp.c:5151:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(out3a);
     ^
src/dsp.c:5152:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(out4a);
     ^
src/dsp.c:5204:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     DSP4_WRITE_WORD(m);
     ^
[ 14%] [ 15%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/Constants.cpp.o
Building CXX object CMakeFiles/rle-lib.dir/src/common/Constants.cpp.o
[ 16%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/SoundExporter.cpp.o
[ 17%] Building CXX object CMakeFiles/rle-lib.dir/src/common/SoundExporter.cpp.o
[ 18%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/display_screen.cpp.o
[ 19%] Building CXX object CMakeFiles/rle-lib.dir/src/common/display_screen.cpp.o
[ 19%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/ScreenExporter.cpp.o
[ 19%] Building CXX object CMakeFiles/rle-lib.dir/src/common/ScreenExporter.cpp.o
[ 20%] [ 21%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/Log.cpp.o
Building CXX object CMakeFiles/rle-lib.dir/src/common/Log.cpp.o
[ 22%] [ 23%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/phosphor_blend.cpp.o
Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/phosphor_blend.cpp.o
[ 24%] [ 25%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/FSNode.cxx.o
Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/FSNode.cxx.o
[ 26%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/RetroAgent.cpp.o
src/memmap.c: In function ‘HeaderRemove’:
src/memmap.c:747:3: warning: value computed is not used [-Wunused-value]
   *(headerCount)++;
   ^
[ 27%] [ 28%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/RleSystem.cxx.o
Building CXX object CMakeFiles/rle-lib.dir/src/environment/RetroAgent.cpp.o
[ 28%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/retro_environment.cpp.o
[ 29%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/rle_screen.cpp.o
[ 30%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/RleSystem.cxx.o
[ 31%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/Deserializer.cxx.o
/home/ubuntu/Retro-Learning-Environment/src/environment/Deserializer.cxx: In member function ‘void Deserializer::getIntArray(int*, size_t&)’:
/home/ubuntu/Retro-Learning-Environment/src/environment/Deserializer.cxx:100:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i = 0 ; i < size ; i++){
                      ^
[ 32%] [ 33%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/Serializer.cxx.o
Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/Settings.cxx.o
[ 33%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/retro_environment.cpp.o
[ 34%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/rle_ram.cpp.o
[ 35%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/rle_state.cpp.o
[ 35%] Building CXX object CMakeFiles/rle-c-lib.dir/src/environment/Random.cxx.o
[ 36%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/rle_screen.cpp.o
[ 37%] [ 38%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/SnesSettings.cpp.o
Building CXX object CMakeFiles/rle-c-lib.dir/src/games/AtariSettings.cpp.o
[ 39%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/Deserializer.cxx.o
/home/ubuntu/Retro-Learning-Environment/src/environment/Deserializer.cxx: In member function ‘void Deserializer::getIntArray(int*, size_t&)’:
/home/ubuntu/Retro-Learning-Environment/src/environment/Deserializer.cxx:100:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i = 0 ; i < size ; i++){
                      ^
[ 40%] [ 41%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/RomUtils.cpp.o
[ 42%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/Settings.cxx.o
Building CXX object CMakeFiles/rle-c-lib.dir/src/games/GenesisSettings.cpp.o
[ 43%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/RomSettings.cpp.o
[ 43%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/Roms.cpp.o
[ 44%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/ClassicKong.cpp.o
[ 45%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/FZero.cpp.o
[ 46%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/Serializer.cxx.o
[ 47%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/rle_ram.cpp.o
[ 48%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/StreetFighterII.cpp.o
[ 49%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/rle_state.cpp.o
[ 50%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/MortalKombat.cpp.o
[ 50%] Building CXX object CMakeFiles/rle-lib.dir/src/environment/Random.cxx.o
[ 51%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/Wolfenstein.cpp.o
[ 52%] Building CXX object CMakeFiles/rle-lib.dir/src/games/SnesSettings.cpp.o
[ 53%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/AtariCollection.cpp.o
[ 53%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/Seaquest.cpp.o
[ 54%] Building CXX object CMakeFiles/rle-lib.dir/src/games/AtariSettings.cpp.o
[ 55%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/TetrisAndDrMario.cpp.o
[ 56%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/NBAGiveNGo.cpp.o
[ 57%] Building CXX object CMakeFiles/rle-lib.dir/src/games/RomUtils.cpp.o
[ 58%] Building CXX object CMakeFiles/rle-lib.dir/src/games/GenesisSettings.cpp.o
[ 59%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/Boxing.cpp.o
[ 60%] Building CXX object CMakeFiles/rle-lib.dir/src/games/RomSettings.cpp.o
[ 61%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/Aladdin.cpp.o
[ 62%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/FinalFight.cpp.o
[ 62%] Building CXX object CMakeFiles/rle-lib.dir/src/games/Roms.cpp.o
[ 62%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/SonicTheHedgehog.cpp.o
[ 63%] [ 64%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/SuperMarioAllStarsNoRight.cpp.o
Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/ClassicKong.cpp.o
[ 65%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/MortalKombat2Players.cpp.o
[ 66%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/SuperMarioAllStars.cpp.o
[ 67%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/FZero.cpp.o
[ 68%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/GradiusIII.cpp.o
[ 69%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/BustAMove.cpp.o
[ 70%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/StreetFighterII.cpp.o
[ 71%] Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/SuperMarioWorld.cpp.o
[ 71%] [ 72%] [ 73%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/MortalKombat.cpp.o
Building CXX object CMakeFiles/rle-c-lib.dir/src/games/supported/FZeroNoSpeed.cpp.o
Building C object CMakeFiles/rle-c-lib.dir/src/external/TinyMT/tinymt32.c.o
[ 74%] Building CXX object CMakeFiles/rle-c-lib.dir/src/os_dependent/FSNodePOSIX.cxx.o
libretro/libretro.c: In function ‘snes_init’:
libretro/libretro.c:619:18: warning: ignoring return value of ‘posix_memalign’, declared with attribute warn_unused_result [-Wunused-result]
    posix_memalign((void**)&GFX.Screen, 16, GFX.Pitch * 512 * sizeof(uint16));
                  ^
Linking CXX shared library ../rle_python_interface/librle_c.so
[ 75%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/Wolfenstein.cpp.o
[ 76%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/AtariCollection.cpp.o
[ 76%] Built target rle-c-lib
[ 76%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/Seaquest.cpp.o
[ 77%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/TetrisAndDrMario.cpp.o
[ 78%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/NBAGiveNGo.cpp.o
[ 79%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/Boxing.cpp.o
[ 80%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/Aladdin.cpp.o
[ 81%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/FinalFight.cpp.o
[ 81%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/SonicTheHedgehog.cpp.o
[ 82%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/SuperMarioAllStarsNoRight.cpp.o
[ 83%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/MortalKombat2Players.cpp.o
[ 84%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/SuperMarioAllStars.cpp.o
[ 85%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/GradiusIII.cpp.o
[ 86%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/BustAMove.cpp.o
[ 87%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/SuperMarioWorld.cpp.o
[ 87%] Building CXX object CMakeFiles/rle-lib.dir/src/games/supported/FZeroNoSpeed.cpp.o
[ 88%] Building C object CMakeFiles/rle-lib.dir/src/external/TinyMT/tinymt32.c.o
[ 89%] Building CXX object CMakeFiles/rle-lib.dir/src/os_dependent/FSNodePOSIX.cxx.o
Linking CXX shared library ../librle.so
[ 89%] Built target rle-lib
[ 90%] No install step for 'snes9x2010_libretro'
[ 91%] Completed 'snes9x2010_libretro'
[ 91%] Built target snes9x2010_libretro
make: *** [all] Error 2

**Comment by nadavbh12** [comment]
I believe this is the same issue as #19 .
