### ISSUE TITLE
Install RLE on CentOS Linux release 7.2.1511

### ISSUE THREAD

**Issue by boche** [nadavbh12/Retro-Learning-Environment#21]
I am trying to install rle on centos with 
`pip install rle-python-interface`,

but always failed because of 
`/tmp/pip-build-mm00sro_/rle-python-interface/src/environment/RetroAgent.cpp:10:28: fatal error: alsa/asoundlib.h: No such file or directory
     #include <alsa/asoundlib.h>`

I have done a few research on installing libasound2 on centos, but with no luck. The install log is attached here [install.txt](https://github.com/nadavbh12/Retro-Learning-Environment/files/901290/install.txt), any idea how to overcome this?

**Comment by nadavbh12** [comment]
Please try the following:
1. clone the repository.
2. Put all the [alsa includes](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/src/environment/RetroAgent.cpp#L10) in RetroAgent.cpp in an `ifdef` block:
```
#ifndef __USE_SDL
#include <alsa/asoundlib.h>
#include <alsa/asoundlib.h>
#include <alsa/control.h>
#endif
```
These aren't required unless you want SDL and sound. In that case you'd need to install alsa.
Let me know if it worked.

**Comment by boche** [comment]
I managed to install the pip package by installing libsdl, libsdl_image, libsdl_gfx and alsa. Thanks. By the way, how to record videos for evaluation?

**Comment by boche** [comment]
a script to set up environment on cents 7.0

`
mkdir ~/opt
cd ~/opt
wget ftp://195.220.108.108/linux/opensuse/distribution/13.2/repo/oss/suse/x86_64/libSDL_gfx-devel-2.0.25-2.1.3.x86_64.rpm
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/alsa-lib-devel-1.1.1-1.el7.x86_64.rpm
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/SDL-devel-1.2.15-14.el7.x86_64.rpm
wget https://www.libsdl.org/projects/SDL_image/release/SDL_image-devel-1.2.12-1.x86_64.rpm
rpm2cpio *rpm | cpio -idv


# add in bashrc
export CMAKE_INCLUDE_PATH=“$HOME/opt/usr/include”:$CMAKE_INCLUDE_PATH
export CMAKE_LIBRARY_PATH=“$HOME/opt/usr/lib64”:$CMAKE_LIBRARY_PATH
export CPATH=“$HOME/opt/usr/include":$CPATH

pip install rle-python-interface
`

**Comment by nadavbh12** [comment]
Thanks for sharing this.
Recording videos isn't supported in RLE directly, however, you can easily use existing Python packages to do so. If you use [gym-rle](https://github.com/nadavbh12/gym-rle), you can use gym's video recording.
