### ISSUE TITLE
ImportError: cannot import name 'RLEInterface'

### ISSUE THREAD

**Issue by IvanKush** [nadavbh12/Retro-Learning-Environment#28]
trying to launch python example, get an error `ImportError: cannot import name 'RLEInterface' `
https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/doc/examples/python_example.py

**Comment by nadavbh12** [comment]
Haven't encountered this issue before. You sure it isn't due to some conflict with gym-rle or due to some other python installation issue?

**Comment by abcp4** [comment]
I have the same error under python 3

**Comment by nadavbh12** [comment]
Could you provide some more details? what are you trying to run?
Are you able to run the [python_example](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/doc/examples/python_example.py)?

**Comment by steph-w** [comment]
I have the same issue running this snippet in python 3 jupyter notebook, after installing with `pip install rle-python-interface`
<img width="925" alt="screen shot 2017-10-01 at 5 43 14 pm" src="https://user-images.githubusercontent.com/17522415/31060947-57cd1d9e-a6d0-11e7-8458-2da0e6cd9ca7.png">

**Comment by steph-w** [comment]
Actually this was an easy fix for me, just make sure you're pointing PYTHONPATH to where your python packages are installed. So for me it was something like 
`export PYTHONPATH=$PYTHONPATH:/home/steph/anaconda3/lib/python3.5/site-packages/rle_python_interface`

**Comment by atypic** [comment]
This is a python 3 / python 2 incompability with respect to how imports are handled. You can fix it by for instance changing __init__.py to 

`from .rle_python_interface import *`

but this might break py2 compat. But who still uses py2 anyway.
