### ISSUE TITLE
In Street Fighter II, rle.game_over() automatically set to true in the middle of the game

### ISSUE THREAD

**Issue by yanpanlau** [nadavbh12/Retro-Learning-Environment#30]
Thanks again for the great work. In Street Fighter II. I notice that the game will automatically terminate in the middle of the episode. To be specific:  rle.game_over() will automatic turn to true in the middle of the game. I looked at src/games/supported/StreetFighterII.cpp but I didn't aware where the terminal condition is set. Could you please help?

**Comment by nadavbh12** [comment]
The terminal state is updated when on of the following occurs:
1. You run out of [time](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/src/games/supported/StreetFighterII.cpp#L90)
2. You [win twice.](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/src/games/supported/StreetFighterII.cpp#L101)
3. You [lose twice](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/src/games/supported/StreetFighterII.cpp#L104) .

It might be that the address the information is taken from is incorrect. Unfortunately, I won't be able to check for the correct addresses soon. You can try validating the addresses by using an emulator that displays the memory (such as BizHawk for windows).
You can learn more about this in our [wiki page](https://github.com/nadavbh12/Retro-Learning-Environment/wiki/How-to-add-a-new-game).

**Comment by yanpanlau** [comment]
Thanks. Can I ask few more questions?

1) How can I set the game difficulty? I try to hack into StreetFighterII.cpp but I still not able to enter Option Menu. I also try to change it to manual mode but it doesn't work either.

2) Is there anyway I can setup 2 AI agent to play each other under V.S. mode?

**Comment by shairoz** [comment]
1. All game menu settings can be modified under the "getStartingActions" function. Simply configure the keys required for choosing a difficulty. 
Another way which might be possible is to access the memory address in which the difficulty is indicated and change it's value.

2. it is possible, have a look at the "MortalKombat2players" files for a notion on how can it be done.
