### ISSUE TITLE
fix setup.py

### ISSUE THREAD

**Issue by gravitino** [nadavbh12/Retro-Learning-Environment#31]
Please change
cmake_args = ' -DBUILD_EXAMPLES=OFF -DBUILD_PYTHON=ON'
to
cmake_args = ' -DBUILD_EXAMPLES=OFF -DBUILD_PYTHON=ON -DUSE_SDL=ON'
and make the world a better place. Great Work BTW!

**Comment by nadavbh12** [comment]
Thanks @gravitino !
Many implementations of RL algorithms use their own display interface (Gym for example), therefore we prefer not to add this dependency if not necessary.
