### ISSUE TITLE
Snes9X

### ISSUE THREAD

**Issue by abcp4** [nadavbh12/Retro-Learning-Environment#33]
Hello, i would like to know if there is some way to set the options of the snes9x emulator, such as background removal, filters disabling and fast-foward.

**Comment by nadavbh12** [comment]
These aren't available through RLE.
I'd check if these options are frontend options, as in, implemented by the software wrapping the emulator with a GUI such as RetroArch. Or if it's part of the backend, as in part of the Snes9x code.
If it's the latter case, you should be able to set these in RetroAgent.cpp.
