### ISSUE TITLE
Python quick start

### ISSUE THREAD

**Issue by njustesen** [nadavbh12/Retro-Learning-Environment#34]
I have troubles using the python interface.
Can you give a more detailed walkthrough of how to get it to work?

After 
`mkdir build && cd build`
it cannot find the CMakeLists.txt file. Should I just build it from the root?

In the python_example.py I need to import the interface like this: 
`from rle_python_interface.rle_python_interface import RLEInterface`
In order to get RLEInterface.

But when I run the file, I get 
`File "/home/noju/Documents/Retro-Learning-Environment/rle_python_interface/rle_python_interface.py", line 108, in setInt
    rle_lib.setInt(self.obj, key, value)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type`

**Comment by nadavbh12** [comment]
You don't need to build RLE manually if you intent to use Python.
setup.py does that for you.

All you need to do is:
`pip install --user .`

Remove the build directory you created from earlier for it work.

**Comment by njustesen** [comment]
Thanks. 
Now when I run python_example.py I get:
`OSError: /home/noju/Documents/Retro-Learning-Environment/rle_python_interface/librle_c.so: cannot open shared object file: No such file or directory`

**Comment by nadavbh12** [comment]
hmm... Maybe your repo is dirty from before.
Try to  re-downloading it and re-install.

**Comment by deepy** [comment]
I'm seeing the same issue, both with the librle_c.so and with the python script.
