### ISSUE TITLE
[Question] What is the core_file in the python example?

### ISSUE THREAD

**Issue by fernandaathayde** [nadavbh12/Retro-Learning-Environment#37]
Hi, I've been trying to run the example_python file, and I was stuck with the core_file parameter, I was wondering which core_file is it? And is it a file that I should download from elsewhere? At first i thought it was a file inside the lib itself, but I couldn't get myself to find it.
Also I was considering to use this API in an academic project, so I would like to know if is there any documentation available .
Thanks in advance.

**Comment by nadavbh12** [comment]
The core file is created when you compile the project.
After you compile it, using the instruction in the readme, enter the build directory, and run the following command:
`../doc/examples/sharedLibraryInterfaceExample ../roms/classic_kong.smc ../snes9x2010/snes9x2010_libretro.so`

You can find RLE's paper [here](https://arxiv.org/abs/1611.02205).
We don't have thorough documentation, though we have examples of usage in [Python](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/doc/examples/python_example.py) and in [C++](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/doc/examples/sharedLibraryInterfaceExample.cpp)

If you're familiar with Gym, you can also use [gym-rle](https://github.com/nadavbh12/gym-rle) to use the standard Gym API.
(We also have a Lua API, though I doubt you want to use that one...).
