### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tohnperfect** [nadavbh12/Retro-Learning-Environment#9]
It stopped compiling at 17% without a clue,

> [ 15%] No install step for 'genesis_plus_gx_libretro'
> [ 15%] Completed 'genesis_plus_gx_libretro'
> [ 15%] Built target genesis_plus_gx_libretro
> [ 16%] No install step for 'snes9x2010_libretro'
> [ 17%] Completed 'snes9x2010_libretro'
> [ 17%] Built target snes9x2010_libretro
> make: *** [all] Error 2

Any suggestion please?

**Comment by nadavbh12** [comment]
Are you compiling using the cmake command or via pip install?

**Comment by tohnperfect** [comment]
I was following the instruction in the README.md,

> $ mkdir build && cd build
> $ cmake -DUSE_SDL=ON -DBUILD_EXAMPLES=ON ..
> $ make -j 4

which is cmake.

**Comment by nadavbh12** [comment]
Please try checking out v1.0.2 and let me know if that works out.

**Comment by tohnperfect** [comment]
v1.0.2 of?

**Comment by nadavbh12** [comment]
Of RLE. As in `git checkout v1.0.2`

**Comment by tohnperfect** [comment]
With v1.0.2, I got stuck at the same point as follows,

> [ 15%] No install step for 'stella_libretro'
> [ 16%] Completed 'stella_libretro'
> [ 16%] Built target stella_libretro
> libretro/libretro.c: In function ‘snes_init’:
> libretro/libretro.c:619:18: warning: ignoring return value of ‘posix_memalign’, declared with attribute warn_unused_result [-Wunused-result]
>     posix_memalign((void**)&GFX.Screen, 16, GFX.Pitch * 512 * sizeof(uint16));
>                   ^
> [ 17%] No install step for 'snes9x2010_libretro'
> [ 18%] Completed 'snes9x2010_libretro'
> [ 18%] Built target snes9x2010_libretro
> make: *** [all] Error 2

**Comment by nadavbh12** [comment]
What's your OS?
Please post the entire output of the make.

**Comment by tohnperfect** [comment]
> Scanning dependencies of target snes9x2010_libretro
> Scanning dependencies of target stella_libretro
> Scanning dependencies of target rle-c-lib
> [  1%] Creating directories for 'snes9x2010_libretro'
> [  2%] Creating directories for 'stella_libretro'
> [  3%] Performing download step (git clone) for 'snes9x2010_libretro'
> [  4%] Performing download step (git clone) for 'stella_libretro'
> Cloning into 'snes9x2010'...
> Cloning into 'stella-libretro'...
> [  4%] Building CXX object CMakeFiles/rle-c-lib.dir/rle_python_interface/rle_c_wrapper.cpp.o
> [  5%] Building CXX object CMakeFiles/rle-c-lib.dir/src/rle_interface.cpp.o
> In file included from /home/localadmin/DATA/git/RLE102/Retro-Learning-Environment-1.0.2/src/os_dependent/../environment/../common/display_screen.h:24:0,
>                  from /home/localadmin/DATA/git/RLE102/Retro-Learning-Environment-1.0.2/src/os_dependent/../environment/RleSystem.hxx:37,
>                  from /home/localadmin/DATA/git/RLE102/Retro-Learning-Environment-1.0.2/src/os_dependent/SettingsUNIX.hxx:23,
>                  from /home/localadmin/DATA/git/RLE102/Retro-Learning-Environment-1.0.2/src/rle_interface.cpp:33:
> /home/localadmin/DATA/git/RLE102/Retro-Learning-Environment-1.0.2/src/os_dependent/../environment/../common/../environment/RetroAgent.h:10:30: fatal error: SDL/SDL_rotozoom.h: No such file or directory
>  #include "SDL/SDL_rotozoom.h"
>                               ^
> compilation terminated.
> [  6%] Building CXX object CMakeFiles/rle-c-lib.dir/src/common/Constants.cpp.o
> make[2]: *** [CMakeFiles/rle-c-lib.dir/src/rle_interface.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/rle-c-lib.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> [  7%] No update step for 'stella_libretro'
> [  8%] No patch step for 'stella_libretro'
> [  9%] No configure step for 'stella_libretro'
> [ 10%] Performing build step for 'stella_libretro'
> make[3]: warning: jobserver unavailable: using -j1. Add `+' to parent make rule.
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> [ 12%] No update step for 'snes9x2010_libretro'
> [ 12%] No patch step for 'snes9x2010_libretro'
> [ 13%] No configure step for 'snes9x2010_libretro'
> [ 14%] Performing build step for 'snes9x2010_libretro'
> make[3]: warning: jobserver unavailable: using -j1. Add `+' to parent make rule.
> src/apu.c: In function ‘spc_copier_copy_int’:
> src/apu.c:1240:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   SET_LE16( s, state );
>   ^
> src/apu.c:1242:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   return GET_LE16( s );
>   ^
> src/dsp.c: In function ‘DSP4_READ_WORD’:
> src/dsp.c:3307:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   out = READ_WORD(DSP4.parameters + DSP4.in_index);
>   ^
> src/dsp.c: In function ‘DSP4_READ_DWORD’:
> src/dsp.c:3317:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   out = READ_DWORD(DSP4.parameters + DSP4.in_index);
>   ^
> src/dsp.c: In function ‘DSP4_OP01’:
> src/dsp.c:3416:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD((DSP4.world_x + DSP4.world_xenv) >> 16);
>    ^
> src/dsp.c:3417:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_x2);
>    ^
> src/dsp.c:3418:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.world_y >> 16);
>    ^
> src/dsp.c:3419:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_y2);
>    ^
> src/dsp.c:3444:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.segments);
>    ^
> src/dsp.c:3470:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
>      ^
> src/dsp.c:3471:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c:3472:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c: In function ‘DSP4_OP07’:
> src/dsp.c:3634:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_x2);
>    ^
> src/dsp.c:3635:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_y2);
>    ^
> src/dsp.c:3660:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.segments);
>    ^
> src/dsp.c:3686:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
>      ^
> src/dsp.c:3687:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c:3688:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c: In function ‘DSP4_OP08’:
> src/dsp.c:3861:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   DSP4_WRITE_BYTE(win_left  & 0xff);
>   ^
> src/dsp.c:3862:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   DSP4_WRITE_BYTE(win_right & 0xff);
>   ^
> src/dsp.c:3941:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>     DSP4_WRITE_WORD(DSP4.segments);
>     ^
> src/dsp.c:4022:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>       DSP4_WRITE_WORD(DSP4.poly_ptr[polygon][0]);
>       ^
> src/dsp.c:4023:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>       DSP4_WRITE_BYTE(x_left  & 0xff);
>       ^
> src/dsp.c:4024:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>       DSP4_WRITE_BYTE(x_right & 0xff);
>       ^
> src/dsp.c:4042:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>   DSP4_WRITE_WORD(0);
>   ^
> src/dsp.c: In function ‘DSP4_OP0B’:
> src/dsp.c:4092:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(1);
>    ^
> src/dsp.c:4095:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_BYTE(sp_x & 0xff);
>    ^
> src/dsp.c:4096:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_BYTE(sp_y & 0xff);
>    ^
> src/dsp.c:4097:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(sp_attr);
>    ^
> src/dsp.c:4119:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(0);
>    ^
> src/dsp.c: In function ‘DSP4_OP09’:
> src/dsp.c:4233:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>     DSP4_WRITE_WORD(world_spx);
>     ^
> src/dsp.c: In function ‘DSP4_OP0D’:
> src/dsp.c:4444:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD((DSP4.world_x + DSP4.world_xenv) >> 16);
>    ^
> src/dsp.c:4445:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_x2);
>    ^
> src/dsp.c:4446:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.world_y >> 16);
>    ^
> src/dsp.c:4447:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_y2);
>    ^
> src/dsp.c:4473:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.segments);
>    ^
> src/dsp.c:4500:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
>      ^
> src/dsp.c:4501:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c:4502:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c: In function ‘DSP4_OP0F’:
> src/dsp.c:4636:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD((DSP4.world_x + DSP4.world_xenv) >> 16);
>    ^
> src/dsp.c:4637:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_x2);
>    ^
> src/dsp.c:4638:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.world_y >> 16);
>    ^
> src/dsp.c:4639:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_y2);
>    ^
> src/dsp.c:4665:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.segments);
>    ^
> src/dsp.c:4701:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>       DSP4_WRITE_WORD(color);
>       ^
> src/dsp.c:4725:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
>      ^
> src/dsp.c:4726:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c:4727:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c: In function ‘DSP4_OP10’:
> src/dsp.c:4872:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_x2);
>    ^
> src/dsp.c:4873:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.view_y2);
>    ^
> src/dsp.c:4898:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    DSP4_WRITE_WORD(DSP4.segments);
>    ^
> src/dsp.c:4931:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>       DSP4_WRITE_WORD(color);
>       ^
> src/dsp.c:4962:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(DSP4.poly_ptr[0][0]);
>      ^
> src/dsp.c:4963:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((y_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c:4964:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD((x_scroll + 0x8000) >> 16);
>      ^
> src/dsp.c: In function ‘DSP4_SetByte’:
> src/dsp.c:5096:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(product);
>      ^
> src/dsp.c:5097:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(product >> 16);
>      ^
> src/dsp.c:5149:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(out1a);
>      ^
> src/dsp.c:5150:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(out2a);
>      ^
> src/dsp.c:5151:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(out3a);
>      ^
> src/dsp.c:5152:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(out4a);
>      ^
> src/dsp.c:5204:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      DSP4_WRITE_WORD(m);
>      ^
> src/memmap.c: In function ‘HeaderRemove’:
> src/memmap.c:747:3: warning: value computed is not used [-Wunused-value]
>    *(headerCount)++;
>    ^
> src/ppu.c: In function ‘S9xUpdateScreen’:
> src/ppu.c:2301:22: warning: array subscript is above array bounds [-Warray-bounds]
>    for (j = i; windows[j] != PPU.Window1Right + 1; j++) ;
>                       ^
> src/ppu.c:2308:22: warning: array subscript is above array bounds [-Warray-bounds]
>    for (j = i; windows[j] != PPU.Window2Right + 1; j++) ;
>                       ^
> src/seta.c: In function ‘S9xSetST010’:
> src/seta.c:546:116: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_Scale(*(int16 *) &Memory.SRAM[0x0004], *(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int32 *) Memory.SRAM[0x0010], (int32 *) Memory.SRAM[0x0014]);
>                                                                                                                     ^
> src/seta.c:546:147: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_Scale(*(int16 *) &Memory.SRAM[0x0004], *(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int32 *) Memory.SRAM[0x0010], (int32 *) Memory.SRAM[0x0014]);
>                                                                                                                                                    ^
> src/seta.c:575:86: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_Multiply(*(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int32 *) Memory.SRAM[0x0010]);
>                                                                                       ^
> src/seta.c:651:117: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_Rotate(*(int16 *) &Memory.SRAM[0x0004], *(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int16 *) Memory.SRAM[0x0010], (int16 *) Memory.SRAM[0x0012]);
>                                                                                                                      ^
> src/seta.c:651:148: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_Rotate(*(int16 *) &Memory.SRAM[0x0004], *(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int16 *) Memory.SRAM[0x0010], (int16 *) Memory.SRAM[0x0012]);
>                                                                                                                                                     ^
> src/seta.c:680:82: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_OP01(*(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int16 *)Memory.SRAM[0x0000], (int16 *) Memory.SRAM[0x0002], (int16 *) Memory.SRAM[0x0004], (int16 *) Memory.SRAM[0x0010]);
>                                                                                   ^
> src/seta.c:680:112: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_OP01(*(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int16 *)Memory.SRAM[0x0000], (int16 *) Memory.SRAM[0x0002], (int16 *) Memory.SRAM[0x0004], (int16 *) Memory.SRAM[0x0010]);
>                                                                                                                 ^
> src/seta.c:680:143: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_OP01(*(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int16 *)Memory.SRAM[0x0000], (int16 *) Memory.SRAM[0x0002], (int16 *) Memory.SRAM[0x0004], (int16 *) Memory.SRAM[0x0010]);
>                                                                                                                                                ^
> src/seta.c:680:174: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>      ST010_OP01(*(int16 *) &Memory.SRAM[0x0000], *(int16 *) &Memory.SRAM[0x0002], (int16 *)Memory.SRAM[0x0000], (int16 *) Memory.SRAM[0x0002], (int16 *) Memory.SRAM[0x0004], (int16 *) Memory.SRAM[0x0010]);
>                                                                                                                                                                               ^
> [ 15%] No install step for 'stella_libretro'
> [ 16%] Completed 'stella_libretro'
> [ 16%] Built target stella_libretro
> libretro/libretro.c: In function ‘snes_init’:
> libretro/libretro.c:619:18: warning: ignoring return value of ‘posix_memalign’, declared with attribute warn_unused_result [-Wunused-result]
>     posix_memalign((void**)&GFX.Screen, 16, GFX.Pitch * 512 * sizeof(uint16));
>                   ^
> [ 17%] No install step for 'snes9x2010_libretro'
> [ 18%] Completed 'snes9x2010_libretro'
> [ 18%] Built target snes9x2010_libretro
> make: *** [all] Error 2
>

**Comment by tohnperfect** [comment]
I checked again I failed to install  `libsdl-image1.2-dev` which I thought I already solved the problem of installing this dependecy.
